version: "3.9"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

  sensorobservationbackend:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
      - redis
    ports:
      - '3000:3000' 
    
volumes:
  db-data:             
