version: "3"
services:
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
    expose:
    - 6379
    restart:
    	always
    command: redis-server --appendonly yes
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

  sensorobservationbackend:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
    depends_on:
    ports:
      - '3000:3000' 
    
volumes:
  db-data:             
